### ISSUE TITLE
feat: Create end to end workflow

### ISSUE THREAD

**Issue by lasselundstenjensen** [NovoNordisk-OpenSource/decentralized-tech-radar#18]
**This means**
- Having a CLI tool that can read "something" from a tech radar spec
- Definition exists for how to write basic tech radar spec file — meaning entries can be split into quadrants and rings and with x-amount of metadata for each point
- Having the CLI tool generate something renderable from the tech radar spec file (e.g. HTML or similar)

**Comment by lasselundstenjensen** [comment]
This can be broken down into separate issues (several for each of the above points, probably).

**Comment by Slug-Boi** [comment]
Closed due to being split up into smaller issues and turned into an epic
