### ISSUE TITLE
feat: The CLI must be able to fetch (i.e. download) a tech radar specification file from one Git repository (any Git, not just GitHub).

### ISSUE THREAD

**Issue by lasselundstenjensen** [NovoNordisk-OpenSource/decentralized-tech-radar#41]
Acceptance Criteria:
(Also part of 2. on issue [33](https://github.com/orgs/NovoNordisk-OpenSource/projects/2/views/1?pane=issue&itemId=56750417)
The fetched files must be fetch-able from at minimum the root level / of the provided Git repository. For now, credentials are not part of the scope and all the Git repositories are assumed accessible from the calling context (e.g. workflow, machine etc.).

**Comment by Slug-Boi** [comment]
We have tested the current sparse-checkout method using GitHub and Gitlab and it works with both so this should mean that it is a universal git based approach
