### ISSUE TITLE
[RQST] feat: Spec-file Header Verifier

### ISSUE THREAD

**Issue by August-Brandt** [NovoNordisk-OpenSource/decentralized-tech-radar#60]
Check that a given csv specfiles files contains the correct header.

So it merely assumes that the data underneath the header is formatted correctly if the header is correct.

A feature that Merger and Fetcher can call independently.

**Comment by Slug-Boi** [comment]
Would suggest making a further issue for checking data integrity

**Comment by Haruyzal** [comment]
> Would suggest making a further issue for checking data integrity

Agreed. I'll make the issue, but it might have to wait until next sprint. We'll see :)
